import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Usage',
      link: {
        type: 'doc',
        id: 'usage/index',
      },
      items: [{type: 'autogenerated', dirName: 'usage'}],
    },
    {
      type: 'category',
      label: 'Architecture Decision Records',
      link: {
        type: 'doc',
        id: 'adrs/index',
      },
      items: [{type: 'autogenerated', dirName: 'adrs'}],
    },
    {
      type: 'category',
      label: 'Specifications',
      link: {
        type: 'doc',
        id: 'specs/index',
      },
      items: [{type: 'autogenerated', dirName: 'specs'}],
    },
  ],
  apiSidebar: [
    {
      type: 'category',
      label: 'API Reference',
      items: [{type: 'autogenerated', dirName: 'api'}],
    },
  ],
};

export default sidebars;
